#!/usr/bin/python

import sys

file_in = open(sys.argv[1],"r")
file_out = open(sys.argv[2],"w")

line_in = file_in.readline()
line_in_split = line_in.split(" ")

file_out.write("Nome stazione\n")
file_out.write(line_in_split[1].strip() + "\n")
file_out.write(line_in_split[0].strip() + "\n")
file_out.write("------SEZIONE TEMP-------- (riga 04)\n")
file_out.write(line_in_split[2].strip() + "\n")
file_out.write(line_in_split[26].strip() + "\n")
file_out.write(line_in_split[27].strip() + "\n")
file_out.write(line_in_split[28].strip() + "\n")
file_out.write(line_in_split[29].strip() + "\n")
file_out.write("0\n")
file_out.write("0\n")
file_out.write("0\n")
file_out.write("0\n")
file_out.write("0\n")
file_out.write("0\n")
file_out.write("------SEZIONE UMID-------- (riga 16)\n")
file_out.write(line_in_split[3].strip() + "\n")
file_out.write(line_in_split[58].strip() + "\n")
file_out.write(line_in_split[59].strip() + "\n")
file_out.write(line_in_split[60].strip() + "\n")
file_out.write(line_in_split[61].strip() + "\n")
file_out.write("------SEZIONE DEW-------- (riga 22)\n")
file_out.write(line_in_split[4].strip() + "\n")
file_out.write(line_in_split[62].strip() + "\n")
file_out.write(line_in_split[63].strip() + "\n")
file_out.write(line_in_split[64].strip() + "\n")
file_out.write(line_in_split[65].strip() + "\n")
file_out.write("------SEZIONE BARO-------- (riga 28)\n")
file_out.write(line_in_split[10].strip() + "\n")
file_out.write(line_in_split[34].strip() + "\n")
file_out.write(line_in_split[35].strip() + "\n")
file_out.write(line_in_split[36].strip() + "\n")
file_out.write(line_in_split[37].strip() + "\n")
file_out.write("------SEZIONE VENTO--------- (riga 34)\n")
file_out.write(line_in_split[6].strip() + "\n")
file_out.write(line_in_split[11].strip() + "\n")
file_out.write(line_in_split[30].strip() + "\n")
file_out.write(line_in_split[32].strip() + "\n")
file_out.write(line_in_split[31].strip() + "\n")
file_out.write("------SEZIONE PRECIPITAZIONI------ (riga 40)\n")
file_out.write(line_in_split[9].strip() + "\n")
file_out.write("0\n")
file_out.write("0\n")
file_out.write("0\n")
file_out.write(line_in_split[19].strip() + "\n")
file_out.write(line_in_split[20].strip() + "\n")

file_in.close()
file_out.close()

sys.exit(0)
